vault:
  injector:
    enabled: false
  server:
    dataStorage:
      storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host vault.172-28-0-3.nip.io
      tls:
        - secretName: vault-tls-certificate
          hosts:
            - *host
    dev:
      enabled: true  # TODO disable vault dev mode
